### ISSUE TITLE
Reading variables without loading entire Netcdf File. 

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#1]
Currently we support reading an entire Netcdf file into memory from HDFS.
While it is a useful feature, we should be able to read only the necessary variables from HDFS and save memory and file i/o time (by reading less). 

I was thinking of a way to compute variable offsets in Netcdf files and if there were any Netcdf api that does that. This is sort of the "missing-link"  feature that I've been searching for. Given this, we should be able to use binaryRecords to only load in the byte-slices of a file that the user requests.

Feel free to post on this thread and update the issue.

**Comment by BrianWilson1** [comment]
I don't think the netCDF API reveals the offset of variables (arrays) within the file.  This is _internal_
to the netCDF library.  It's even worse for netCDF4 (HDF5 underneath).  Each variable can be
compressed and then chunked, with the chunks basically a linked list of blocks within the file.

Getting netCDF4/HDF5 to respect HDFS blocking is a hard problem that goes to the core of
the library.  That is why the HDF5 guys have a project to store their 'chunks' as individual
objects in S3 buckets in order to get parallel I/O.  Also, the blocking size that HDFS uses is
not really appropriate for the HDF5 chunks.

**Comment by rahulpalamuttam** [comment]
Thanks Brian! This is definitely a well known problem - so I had to ask the obvious :) 
I was wondering if there was api for understanding the organization of a netcdf file at the byte-level. If I understand what binaryRecords does, it attempts to treat the HDFS file as a normal file so we can use byte offsets to extract slices of a file. We could potentially extract the compressed chunks within the file knowing at what offsets they live at, then un-compress and put the slices together to get the variable array. It is a pretty involved task, and I probably over-simplified what is really required. It would be nice to have some sort of pointer towards Netcdf/HDF5 file creation for future reference - in case someone wants to tackle the problem for usage in Scispark.

**Comment by chrismattmann** [comment]
I think that #6 took care of this.

**Comment by nealmcb** [comment]
I don't know if it is applicable to your situation, but this presentation talks about indexing netCDF files into HDFS to optimize access, for Hadoop.  It is often possible to use Hadoop I/O Java classes in Spark.  And if not, the ideas may still be useful.
- [Applying Apache Hadoop to NASA’s Big Climate Data Use Cases and Lessons Learned Glenn Tamkin (NASA/CSC)](http://events.linuxfoundation.org/sites/events/files/slides/ApacheCon_NASA_Hadoop.pdf) for MERRA: ApacheCon, 2015-04-13

**Comment by chrismattmann** [comment]
thanks @nealmcb for the info!

**Comment by BrianWilson1** [comment]
Hi Neal,

I looked at your presentation.  I will dig deeper and then I think I'll have some questions for you.

 -- Brian
