### ISSUE TITLE
[Discuss] updates to the sciTensor implementation

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/SciSpark#51]
The current sciTensor implementation can lead lost of metadata properties associated with individual variables from netCDF files. The current implement takes the data from a variable and places it in Abstract tensor, and any metaData is applied to the entire sciTensor. This can make it cumbersome to track metaData associated with a particular variable.

![image](https://cloud.githubusercontent.com/assets/7198635/15908242/80b72e78-2d75-11e6-8130-896fa1aafd6a.png)

It is proposed to mirror the netCDF design while loading the data into the sciTensor, by using a (key, value) pair of (String, HashMap) instead of the current (String, AbstractTensor) implementation. See sciTensor's implementation [here.](https://github.com/SciSpark/SciSpark/blob/master/src/main/scala/org/dia/core/SciTensor.scala) 

![image](https://cloud.githubusercontent.com/assets/7198635/15908226/6ea37c5a-2d75-11e6-9f02-33c640e1c023.png)

This will be a major change to the current API.

**Comment by kwhitehall** [comment]
Closing this discussion issue. The change was discussed and implement in #68.

**Comment by rahulpalamuttam** [comment]
@kwhitehall 
The new design is effectively implemented in [SciDataset](https://github.com/SciSpark/SciSpark/blob/master/src/main/scala/org/dia/core/SciDataset.scala)

I was hesitant to close the issue, because you specifically requested it for SciTensor.
However, (correct me if I'm wrong) SciDataset is SciTensor version 2 and more or less meets the above requirements : A variable dictionary which contain variables each with attributes of their own.
SciDataset also contains global attributes.

The "units" are an attribute.

**Comment by rahulpalamuttam** [comment]
closed as we are migrating to SciDataset
