### ISSUE TITLE
update the masking properties to allow user to enter flag

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/SciSpark#63]
Currently the default value is 0.0 which can pose an issue depending on the variable (as it might be a valid value). The user should be allowed to enter the masked value.

**Comment by rahulpalamuttam** [comment]
The above PR includes 2 ways of masking with different masked values.
1. 
   The AbstractTensor and all implementing classes, have a setMask function.

The function is a little different than the other arithmetic functions in that it modifies the mask variable and returns the same AbstractTensor object reference.

Thus Nd4jt.setMask(100.0) will return the same object reference to Nd4jt.

It still supports the usual method chaining like so
val filtered = Nd4jt.setMask(100.0) <= 241.0.

The change in mask value also only works on the variable in use.

2.
AbstractTensor and implementing classes have a "mask" function which accepts a function of type (Double => Boolean) and an optional Double for the mask value. Rather than setting the default mask, it uses the function to do filtering and mask setting. Since this changes the tensor contents, the function returns a new reference rather than returning the original reference to the tensor.

I've added the corresponding tests to the above PR as well.
1. [setMask](https://github.com/rahulpalamuttam/SciSpark/blob/1161e8efefba73538d62cb91a4fa342f5e4781f3/src/test/scala/org/dia/tensors/BasicTensorTest.scala#L64-L72)
2. [mask](https://github.com/rahulpalamuttam/SciSpark/blob/1161e8efefba73538d62cb91a4fa342f5e4781f3/src/test/scala/org/dia/tensors/BasicTensorTest.scala#L54-L62)

**Comment by kwhitehall** [comment]
Thanks @rahulpalamuttam. PR #65 merged addressing this issue.
