### ISSUE TITLE
SciTensor api changes

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#68]
Discussed with @BrianWilson1 

Our discussion centered around how we interact with SciTensor. Brian mentioned that he wanted to approach the variable and data access in a more pythonic way. 
1. SciTensor should have a set of hardcoded global attributes in a dictionary named "attrs"
   Right now this is done through the METADATA hash table - which the user can edit/change.
2. SciTensor should also have a set of variable attributes named "vars". The variable arrays have attributes as well.
   Right now we have a hash table of AbstactTensors named variables.
3. We should not be relying on the varInUse global variable to change what variable we operate on. Rather we should interact with the underlying variables directly either by doing
   st.vars['varname'].data
   or 
   st.vars['varname'][:]
   The latter python slicing operation as a way to obtain the underlying array.
   Also in scala this will be done through the apply function so
   st.vars('varname')(:)

A bit about the varInUse variable :
It is a global variable that switches which variable array in the SciTensor bundle will be operated on.
The point was to keep the variables in a bundle and avoid method chaining. Also, keep the variables in SciTensors, rather than pulling them out. For example :
st => st('varname') + 2 is a lambda expression of type (SciTensor => SciTensor)
st => st.vars('varname').data + 2 is a lambda expression of type (SciTensor => AbstractTensor)
 To achieve the same effect of the first expression we would need to do
st => { 
           st.vars('varname').data + 2
           st }

@BrianWilson1 - I think I missed a few points here and there. 

 @kwhitehall @chrismattmann 
Thoughts?

**Comment by kwhitehall** [comment]
Couple thoughts. I agree with the sciTensor restructure (1&2). See issue #51 which has a schematic of what is essentially being proposed, unless I misunderstand. 

Regarding 3. I think comes down to the core of how we wish to architect SciSpark. I personally prefer the concept of operations on SciTensors rather than the AbstractTensor - operations on a datatype should return the same datatype, and in terms of the syntax it seems more Spark-like.
Other things to think about re: usecases are:
1. The use case of having an sRDD of sciTensors containing data associated from one file (e.g. MERG) and another sRDD of sciTensors containing data from another file (e.g. TRMM), being easily operated on arithmetically without having to copy the data further (e.g. make an sRDD of sciTensors with the abstractTensors/ data to be used then performing the arithmetic operation). 
2. The usecase where there can be more than one variable to be operated on within an sRDD of sciTensors, e.g. if one is considering a wind field that is usually given and U and V component within on netCDF file. The sciTensor would have the array var for each, and the current operation can be easily facilitated within the sciTensor. 
3. The usecase where a sRDD can contain a sciTensor with multiple AbstractTensors of the same variable (e.g. T for a number of times) and the arithmetic operation should/ could be completed on all the abstractTensors.

Also, we may wish to consider how the provenance of the data interaction would be captured.

**Comment by rahulpalamuttam** [comment]
This is closed as we are migrating to SciDataset
